### ISSUE TITLE
Compatibility with Node 4

### ISSUE THREAD

**Issue by Rudloff** [raphinesse/cordova-plugin-exclude-files#1]
Hello,

I'm using cordova-plugin-exclude-files 0.2.1 with Node 4.7.2 and I get this error when doing `cordova prepare`:
```
Executing script found in plugin cordova-plugin-exclude-files for hook "after_prepare": plugins/cordova-plugin-exclude-files/scripts/exclude-files.js
Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

I guess this is because my Node version is old but it can easily be fixed by adding this at the beginning of  `exclude-files.js`:
```js
"use strict";
```

Except for that the plugin seems to work just fine with Node 4.

**Comment by raphinesse** [comment]
Thanks for reporting this. I'm surprised that it runs on Node 4 at all :grin: 

Can you please tell me if #2 really resolves the problem for you?
