### ISSUE TITLE
Does not work when config.xml is in the www directory

### ISSUE THREAD

**Issue by henkkelder** [raphinesse/cordova-plugin-exclude-files#4]
Your plugin does not work when the config.xml is in the www directory.

**Comment by raphinesse** [comment]
Thanks for reporting! Until now, I did not know that it was also possible to have`config.xml` in `www`. But the docs confirm that. I'll fix this ASAP.

**Comment by raphinesse** [comment]
Fixed in v0.3.2

**Comment by henkkelder** [comment]
Thank you. I can now build:
- using CLI for Android, Seems to do what it should
- using Phonegap build. Does however NOT exclude the files.
