### ISSUE TITLE
Plugin does not do its job in Phonegap build.

### ISSUE THREAD

**Issue by henkkelder** [raphinesse/cordova-plugin-exclude-files#5]
I can include the plugin in my PGB builds. No errors and the plugin is also included in the build.

However, the files that should have been excluded are still present in the build .IPA file for IOS.

The same setup (config.xml etc) does work fine with a CLI  Android build on my own PC.

**Comment by raphinesse** [comment]
Thanks for bringing this to my attention. Unfortunately, [PhoneGap Build doesn't support Cordova hooks](https://github.com/phonegap/build/issues/425#issuecomment-93126212), which is exactly what this plugin uses to do its thing.

I'm sorry to say that I can do nothing but include a note about this in the README. :frowning_face: 

Edit: added note in fb3ad8994e826b93f8d6197d2ecdd881bd2dbe7e

**Comment by henkkelder** [comment]
Danke jedenfals für das Antwort :)


Grüss aus die Niederlande.

**Comment by raphinesse** [comment]
Gern geschehen. Schöne Grüße zurück :relaxed:
